// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.WsdlProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.WsdlProvider")>]
[<assembly: AssemblyDescriptionAttribute("This is a type provider to generate clients for soap services from wsdl")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.WsdlProvider.Runtime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.WsdlProvider"
    let [<Literal>] AssemblyDescription ="This is a type provider to generate clients for soap services from wsdl"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
